services:
  app:
    container_name: fund
    build:
      context: .
      args:
        NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL: ${NEXT_PUBLIC_GITHUB_LATEST_RELEASE_URL}

    ports:
      - "3000:3000"

    restart: always
    env_file:
      - .env

    environment:
      NODE_ENV: production
