-- ========================================================
-- Real-Time Fund (基估宝) - 该文件为会员版
-- ========================================================


-- ========================================================
-- 1. 用户配置表 (user_configs)
-- 用于云端同步用户的所有本地数据
-- ========================================================

CREATE TABLE public.user_configs (
                                     id bigint generated by default as identity not null,
                                     created_at timestamp with time zone not null default now(),
                                     data json null,
                                     updated_at timestamp with time zone null,
                                     user_id uuid not null,
                                     last_device_id text null, -- 1.3.5 新增
                                     ytd_return_rate numeric null, -- 2.2.0 新增
                                     CONSTRAINT user_configs_pkey PRIMARY KEY (id),
                                     CONSTRAINT user_configs_user_id_key UNIQUE (user_id)
) TABLESPACE pg_default;

CREATE INDEX idx_user_configs_ytd_return_rate ON public.user_configs (ytd_return_rate);

-- 启用行级安全（RLS）
ALTER TABLE public.user_configs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_configs_select_own" ON public.user_configs;
DROP POLICY IF EXISTS "user_configs_insert_own" ON public.user_configs;
DROP POLICY IF EXISTS "user_configs_update_own" ON public.user_configs;

CREATE POLICY "user_configs_select_own"
ON public.user_configs
FOR SELECT
                              USING (auth.uid() = user_id);

CREATE POLICY "user_configs_insert_own"
ON public.user_configs
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_configs_update_own"
ON public.user_configs
FOR UPDATE
                      USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- --------------------------------------------------------
-- 全量更新函数 (update_user_config_full)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_user_config_full(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
current_device_id text;
  v_ytd_rate numeric := null;
begin
select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
end if;

insert into public.user_configs (user_id, data, updated_at, last_device_id, ytd_return_rate)
values (auth.uid(), payload::json, now(), p_last_device_id, v_ytd_rate)
    on conflict (user_id) do update
                                 set data = excluded.data,
                                 updated_at = excluded.updated_at,
                                 last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id),
                                 ytd_return_rate = coalesce(v_ytd_rate, public.user_configs.ytd_return_rate);
end;
$$;

GRANT EXECUTE ON FUNCTION public.update_user_config_full(jsonb, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_config_full(jsonb, text, boolean) TO service_role;

-- --------------------------------------------------------
-- 增量更新函数 (update_user_config_partial)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_user_config_partial(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
current_device_id text;
  v_ytd_rate numeric := null;
begin
select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
end if;

  if payload ? 'ytdReturnRate' then
    v_ytd_rate := (payload->>'ytdReturnRate')::numeric;
end if;

update public.user_configs
set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
    updated_at = now(),
    last_device_id = coalesce(p_last_device_id, last_device_id),
    ytd_return_rate = coalesce(v_ytd_rate, ytd_return_rate)
where user_id = auth.uid();
end;
$$;

-- --------------------------------------------------------
-- 获取 YTD 击败用户比例 (get_ytd_percentile)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_ytd_percentile(p_ytd_rate numeric)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
total_count int;
  beat_count int;
BEGIN
SELECT count(*) INTO total_count FROM public.user_configs WHERE user_id <> auth.uid() AND ytd_return_rate IS NOT NULL;
IF total_count < 10 THEN
    RETURN -1; -- Returns -1 to indicate insufficient data
END IF;
SELECT count(*) INTO beat_count
FROM public.user_configs
WHERE user_id <> auth.uid() AND ytd_return_rate IS NOT NULL AND ytd_return_rate < p_ytd_rate;
RETURN round((beat_count::numeric / total_count::numeric) * 100, 2);
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_ytd_percentile(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_ytd_percentile(numeric) TO service_role;

GRANT EXECUTE ON FUNCTION public.update_user_config_partial(jsonb, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_config_partial(jsonb, text, boolean) TO service_role;


-- ========================================================
-- 2. 基金板块数据
-- 包含: fund_related, fund_secid, fund_topic
-- ========================================================

-- --------------------------------------------------------
-- 关联板块表 (fund_related)
-- --------------------------------------------------------
CREATE TABLE public.fund_related (
                                     id bigint generated by default as identity not null,
                                     created_at timestamp with time zone not null default now(),
                                     fund_code character varying null,
                                     related_sector text null,
                                     CONSTRAINT fund_related_pkey PRIMARY KEY (id),
                                     CONSTRAINT fund_related_fund_code_key UNIQUE (fund_code)
) TABLESPACE pg_default;

ALTER TABLE public.fund_related ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to select fund_related"
ON public.fund_related
FOR SELECT
               TO authenticated
               USING (auth.uid() IS NOT NULL);

-- --------------------------------------------------------
-- 基金 SecId 表 (fund_secid)
-- --------------------------------------------------------
CREATE TABLE public.fund_secid (
                                   id bigint generated by default as identity not null,
                                   created_at timestamp with time zone not null default now(),
                                   related_sector text null,
                                   secid character varying null,
                                   CONSTRAINT fund_secid_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE public.fund_secid ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to select fund_secid"
ON public.fund_secid
FOR SELECT
               TO authenticated
               USING (auth.uid() IS NOT NULL);

-- --------------------------------------------------------
-- 基金主题表 (fund_topic)
-- --------------------------------------------------------
CREATE TABLE public.fund_topic (
                                   id bigint generated by default as identity not null,
                                   created_at timestamp with time zone not null default now(),
                                   update_at timestamp with time zone null,
                                   sector_type text null,
                                   sector_id text null,
                                   sector_name text null,
                                   update_frequency text null,
                                   net_inflow bigint null,
                                   change_pct real null,
                                   CONSTRAINT fund_topic_pkey PRIMARY KEY (id),
                                   CONSTRAINT fund_topic_sector_id_key UNIQUE (sector_id),
                                   CONSTRAINT fund_topic_sector_name_key UNIQUE (sector_name)
);

ALTER TABLE public.fund_topic ENABLE ROW LEVEL SECURITY;

CREATE POLICY "允许已登录用户读取基金主题数据"
ON public.fund_topic
FOR SELECT
               TO authenticated
               USING (true);


-- ========================================================
-- 3. 限制流与审计记录
-- ========================================================

-- --------------------------------------------------------
-- OCR 每日调用次数限流表 (ocr_daily_usage)
-- --------------------------------------------------------
CREATE TABLE public.ocr_daily_usage (
                                        id bigint generated by default as identity not null,
                                        user_id uuid not null,
                                        usage_date date not null default current_date,
                                        count int not null default 0,
                                        CONSTRAINT ocr_daily_usage_pkey PRIMARY KEY (id),
                                        CONSTRAINT ocr_daily_usage_unique UNIQUE (user_id, usage_date)
) TABLESPACE pg_default;

-- 索引加速查询
CREATE INDEX idx_ocr_daily_usage_user_date ON public.ocr_daily_usage (user_id, usage_date);

ALTER TABLE public.ocr_daily_usage ENABLE ROW LEVEL SECURITY;

-- 允许已登录用户查看自己的用量
CREATE POLICY "ocr_usage_select_own"
ON public.ocr_daily_usage
FOR SELECT
               TO authenticated
               USING (auth.uid() = user_id);

-- --------------------------------------------------------
-- 原子检查并自增 OCR 用量的函数 (check_and_increment_ocr_usage)
-- 返回: { allowed: boolean, current_count: int, max_limit: int }
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.check_and_increment_ocr_usage(
  p_max_limit int default 10
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
v_user_id uuid := auth.uid();
  v_today date := current_date;
  v_current_count int;
begin
  if v_user_id is null then
    return jsonb_build_object('allowed', false, 'current_count', 0, 'max_limit', p_max_limit, 'error', 'NOT_AUTHENTICATED');
end if;

  -- 尝试 upsert 并原子自增
insert into public.ocr_daily_usage (user_id, usage_date, count)
values (v_user_id, v_today, 1)
    on conflict (user_id, usage_date)
  do update set count = ocr_daily_usage.count + 1
     where ocr_daily_usage.count < p_max_limit
         returning count into v_current_count;

-- 如果没有 returning 结果，说明已达上限（WHERE 条件不满足）
if v_current_count is null then
select count into v_current_count
from public.ocr_daily_usage
where user_id = v_user_id and usage_date = v_today;

return jsonb_build_object('allowed', false, 'current_count', coalesce(v_current_count, 0), 'max_limit', p_max_limit);
end if;

return jsonb_build_object('allowed', true, 'current_count', v_current_count, 'max_limit', p_max_limit);
end;
$$;

GRANT EXECUTE ON FUNCTION public.check_and_increment_ocr_usage(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_and_increment_ocr_usage(int) TO service_role;


-- ========================================================
-- 4. 会员体系 (Membership System)
-- 包含: user_memberships, membership_codes, membership_logs
-- ========================================================

-- --------------------------------------------------------
-- 用户会员状态表 (user_memberships)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_memberships (
                                                       user_id uuid not null,
                                                       tier text not null default 'free', -- 'free' | 'pro'
                                                       is_permanent boolean not null default false,
                                                       expire_at timestamp with time zone null,
                                                       created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    CONSTRAINT user_memberships_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
    ) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_memberships_expire_at ON public.user_memberships (expire_at);

ALTER TABLE public.user_memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_memberships_select_own" ON public.user_memberships;
CREATE POLICY "user_memberships_select_own"
ON public.user_memberships
FOR SELECT
                    TO authenticated
                    USING (auth.uid() = user_id);

-- --------------------------------------------------------
-- 会员兑换码表 (membership_codes)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.membership_codes (
                                                       code text not null,
                                                       tier text not null default 'pro',
                                                       duration_days int not null default 30,
                                                       is_permanent boolean not null default false,
                                                       is_used boolean not null default false,
                                                       used_by uuid null,
                                                       used_at timestamp with time zone null,
                                                       created_at timestamp with time zone not null default now(),
    CONSTRAINT membership_codes_pkey PRIMARY KEY (code),
    CONSTRAINT membership_codes_used_by_fkey FOREIGN KEY (used_by) REFERENCES auth.users(id) ON DELETE SET NULL
    ) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_membership_codes_is_used ON public.membership_codes (is_used);

ALTER TABLE public.membership_codes ENABLE ROW LEVEL SECURITY;

-- 兑换码表不对外部用户开放直接读写，所有操作通过 RPC 存储过程进行

-- --------------------------------------------------------
-- 会员核销流水记录表 (membership_logs)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.membership_logs (
                                                      id bigint generated by default as identity not null,
                                                      user_id uuid not null,
                                                      code text not null,
                                                      action text not null default 'ACTIVATE',
                                                      duration_days int not null default 0,
                                                      created_at timestamp with time zone not null default now(),
    CONSTRAINT membership_logs_pkey PRIMARY KEY (id),
    CONSTRAINT membership_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
    ) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_membership_logs_user_id ON public.membership_logs (user_id);

ALTER TABLE public.membership_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "membership_logs_select_own" ON public.membership_logs;
CREATE POLICY "membership_logs_select_own"
ON public.membership_logs
FOR SELECT
                    TO authenticated
                    USING (auth.uid() = user_id);

-- --------------------------------------------------------
-- 核销兑换码存储过程 (activate_membership_code)
-- 加入 pg_sleep(1) 延迟防线，抵御脚本并发及暴力穷举
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.activate_membership_code(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
v_user_id uuid := auth.uid();
  v_code_row public.membership_codes%rowtype;
  v_mem_row public.user_memberships%rowtype;
  v_new_expire timestamp with time zone;
  v_is_perm boolean := false;
begin
  -- 1. 延迟防线：强制挂起 1 秒，显著压制暴力尝试速率
  PERFORM pg_sleep(1);

  if v_user_id is null then
    return jsonb_build_object('success', false, 'error', 'NOT_AUTHENTICATED', 'message', '请先登录后重新尝试');
end if;

  if p_code is null or trim(p_code) = '' then
    return jsonb_build_object('success', false, 'error', 'INVALID_CODE', 'message', '兑换码不能为空');
end if;

  -- 2. 查询并锁定兑换码
select * into v_code_row
from public.membership_codes
where code = trim(p_code)
    for update;

if v_code_row.code is null then
    return jsonb_build_object('success', false, 'error', 'CODE_NOT_FOUND', 'message', '无效的兑换码，请检查后重试');
end if;

  if v_code_row.is_used then
    return jsonb_build_object('success', false, 'error', 'CODE_ALREADY_USED', 'message', '该兑换码已被使用');
end if;

  -- 3. 查询当前用户会员状态
select * into v_mem_row
from public.user_memberships
where user_id = v_user_id
    for update;

-- 4. 计算新的过期时间与永久状态
if v_code_row.is_permanent then
    v_is_perm := true;
    v_new_expire := '2099-12-31 23:59:59+00'::timestamptz;
else
    if v_mem_row.user_id is not null and v_mem_row.is_permanent then
      v_is_perm := true;
      v_new_expire := '2099-12-31 23:59:59+00'::timestamptz;
else
      -- 若已有未过期时间，则从原有过期时间累加；否则从当前时间累加
      if v_mem_row.user_id is not null and v_mem_row.expire_at is not null and v_mem_row.expire_at > now() then
        v_new_expire := v_mem_row.expire_at + (v_code_row.duration_days || ' days')::interval;
else
        v_new_expire := now() + (v_code_row.duration_days || ' days')::interval;
end if;
      v_is_perm := false;
end if;
end if;

  -- 5. 标记兑换码已使用
update public.membership_codes
set is_used = true,
    used_by = v_user_id,
    used_at = now()
where code = v_code_row.code;

-- 6. 更新或插入用户会员状态
insert into public.user_memberships (user_id, tier, is_permanent, expire_at, updated_at)
values (v_user_id, v_code_row.tier, v_is_perm, v_new_expire, now())
    on conflict (user_id) do update
                                 set tier = excluded.tier,
                                 is_permanent = excluded.is_permanent,
                                 expire_at = excluded.expire_at,
                                 updated_at = now();

-- 7. 写入审计日志
insert into public.membership_logs (user_id, code, action, duration_days)
values (v_user_id, v_code_row.code, 'ACTIVATE', v_code_row.duration_days);

return jsonb_build_object(
        'success', true,
        'tier', v_code_row.tier,
        'is_permanent', v_is_perm,
        'expire_at', v_new_expire,
        'message', '会员开通成功！'
       );
end;
$$;

GRANT EXECUTE ON FUNCTION public.activate_membership_code(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.activate_membership_code(text) TO service_role;

-- --------------------------------------------------------
-- 查询当前用户会员状态存储过程 (get_my_membership_status)
-- 实时在线查询，不缓存至 localStorage
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_my_membership_status()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
v_user_id uuid := auth.uid();
  v_mem_row public.user_memberships%rowtype;
  v_days_remaining numeric := 0;
begin
  if v_user_id is null then
    return jsonb_build_object('is_vip', false, 'tier', 'free', 'is_permanent', false, 'days_remaining', 0, 'expire_at', null);
end if;

select * into v_mem_row
from public.user_memberships
where user_id = v_user_id;

if v_mem_row.user_id is null then
    return jsonb_build_object('is_vip', false, 'tier', 'free', 'is_permanent', false, 'days_remaining', 0, 'expire_at', null);
end if;

  -- 如果不是永久会员，且已过期
  if not v_mem_row.is_permanent and (v_mem_row.expire_at is null or v_mem_row.expire_at <= now()) then
    return jsonb_build_object('is_vip', false, 'tier', 'free', 'is_permanent', false, 'days_remaining', 0, 'expire_at', v_mem_row.expire_at);
end if;

  if v_mem_row.is_permanent then
    v_days_remaining := 99999;
else
    v_days_remaining := round((extract(epoch from (v_mem_row.expire_at - now())) / 86400)::numeric, 1);
end if;

return jsonb_build_object(
        'is_vip', true,
        'tier', v_mem_row.tier,
        'is_permanent', v_mem_row.is_permanent,
        'days_remaining', v_days_remaining,
        'expire_at', v_mem_row.expire_at
       );
end;
$$;

GRANT EXECUTE ON FUNCTION public.get_my_membership_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_membership_status() TO service_role;

-- --------------------------------------------------------
-- 批量生成随机兑换码工具函数 (generate_membership_codes)
-- 供管理员在 SQL Editor 执行，批量生成具有唯一性的兑换码
-- 例如: SELECT public.generate_membership_codes(10, 30, false);
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.generate_membership_codes(
  p_count int default 10,
  p_duration_days int default 30,
  p_is_permanent boolean default false
)
RETURNS TABLE(code text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS
$$
declare
i int := 0;
  v_code text;
  v_tier text := 'pro';
begin
  while i < p_count loop
    -- 生成由大写字母和数字组成的 12 位随机码，格式例如：VIP-XXXX-XXXX
    v_code := 'VIP-' || upper(substring(md5(random()::text || clock_timestamp()::text) from 1 for 4)) || '-' || upper(substring(md5(random()::text || clock_timestamp()::text) from 5 for 4));

    if not exists (select 1 from public.membership_codes mc where mc.code = v_code) then
      insert into public.membership_codes (code, tier, duration_days, is_permanent)
      values (v_code, v_tier, p_duration_days, p_is_permanent);

      code := v_code;
return next;
i := i + 1;
end if;
end loop;
end;
$$;

GRANT EXECUTE ON FUNCTION public.generate_membership_codes(int, int, boolean) TO service_role;


-- --------------------------------------------------------
-- 5. 系统活动福利：限时赠送 2026-07-31 PRO 会员触发器
-- --------------------------------------------------------
-- 1. 批量为存量已注册用户开通/更新为 PRO 会员，有效期至北京时间 2026-07-31 23:59:59
-- INSERT INTO public.user_memberships (user_id, tier, is_permanent, expire_at, updated_at)
-- SELECT id as user_id, 'pro' as tier, false as is_permanent, '2026-07-31 23:59:59+08'::timestamptz as expire_at, now() as updated_at
-- FROM auth.users
-- ON CONFLICT (user_id) DO UPDATE
-- SET tier = 'pro', is_permanent = false, expire_at = '2026-07-31 23:59:59+08'::timestamptz, updated_at = now();

-- 2. 自动赋权触发器函数：在 2026-07-31 23:59:59+08 之前新注册的用户，自动获得 PRO 会员
CREATE OR REPLACE FUNCTION public.on_auth_user_created_grant_pro()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
begin
  if now() <= '2026-07-31 23:59:59+08'::timestamptz then
    insert into public.user_memberships (user_id, tier, is_permanent, expire_at, updated_at)
    values (new.id, 'pro', false, '2026-07-31 23:59:59+08'::timestamptz, now())
    on conflict (user_id) do update
                                      set tier = 'pro',
                                      is_permanent = false,
                                      expire_at = '2026-07-31 23:59:59+08'::timestamptz,
                                      updated_at = now();
end if;
return new;
end;
$$;

DROP TRIGGER IF EXISTS tr_on_auth_user_created_grant_pro ON auth.users;
CREATE TRIGGER tr_on_auth_user_created_grant_pro
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.on_auth_user_created_grant_pro();


